[package]
name = "orx-imp-vec"
version = "0.9.5"
edition = "2021"
authors = ["orxfun <orx.ugur.arikan@gmail.com>"]
description = "ImpVec stands for 'immutable-push-vec'. It wraps a PinnedVec giving it safe abilities to push/extend operations with an immutable reference and a safe api for building self-referencing vectors."
license = "MIT"
repository = "https://github.com/orxfun/orx-imp-vec/"
keywords = ["vec", "array", "split", "fragments", "pinned"]
categories = ["data-structures"]

[dependencies]
orx-fixed-vec = "0.3.3"
orx-pinned-vec = "0.4.3"
orx-split-vec = "0.9.1"
