[package]
name = "orx-imp-vec"
version = "1.0.0"
edition = "2021"
authors = ["orxfun <orx.ugur.arikan@gmail.com>"]
description = "A data structure to enable conveniently building performant self referential collections such as trees, graphs and linked lists."
license = "MIT"
repository = "https://github.com/orxfun/orx-imp-vec/"
keywords = ["vec", "array", "split", "fragments", "pinned"]
categories = ["data-structures", "rust-patterns"]

[dependencies]
orx-fixed-vec = "1.0"
orx-pinned-vec = "1.0"
orx-split-vec = "1.2"
