[package]
name = "orx-imp-vec"
version = "2.5.0"
edition = "2021"
authors = ["orxfun <orx.ugur.arikan@gmail.com>"]
description = "`ImpVec`, standing for immutable push vector 👿, is a data structure which allows appending elements with a shared reference."
license = "MIT"
repository = "https://github.com/orxfun/orx-imp-vec/"
keywords = ["vec", "pinned", "bag", "container", "split"]
categories = ["data-structures", "rust-patterns"]

[dependencies]
orx-pseudo-default = "1.2.0"
orx-pinned-vec = "3.2.0"
orx-fixed-vec = "3.2.0"
orx-split-vec = "3.2.0"
